# Production Training Configuration
# Higher quality training with more checkpoints and evaluation

training:
  # Extended training
  total_timesteps: 1000000
  n_parallel_envs: 6
  
  # Production data split (90/10)
  data_split:
    train: 0.90
    val: 0.10
  
  # More frequent checkpointing for production
  checkpoint:
    save_freq: 50000   # More frequent
    save_best: true
    eval_freq: 5000    # More frequent evaluation
  
  # Optimization
  optimization:
    use_gpu: true
    vec_normalize: true
    n_eval_episodes: 20
  
  # WandB logging
  logging:
    use_wandb: true
    project: "nebula-trade-production"
    entity: null
    log_freq: 500
    verbose: 1
  
  # Extended callbacks
  callbacks:
    - type: "checkpoint"
      params:
        save_freq: 50000
        save_path: null
    - type: "eval"
      params:
        eval_freq: 5000
        n_eval_episodes: 10
    - type: "wandb"
      params:
        log_freq: 500
    - type: "performance_monitor"
      params:
        window_size: 100

# No resume by default
resume:
  enabled: false
  checkpoint_path: null
  reset_timesteps: false
