# Production Model Configuration
# Based on Phase 1 Extended (PROVEN BEST: 29.44% return)

portfolio:
  name: "NIFTY Bank Portfolio - Production"
  version: "v1"

  assets:
    - "HDFCBANK.NS"
    - "ICICIBANK.NS"
    - "SBIN.NS"
    - "AXISBANK.NS"
    - "KOTAKBANK.NS"

  initial_weights:
    mode: "equal"
    cash_buffer: 0.1  # 10% cash initially

  constraints:
    min_weight: 0.0   # No shorting
    max_weight: 1.0   # Max per asset
    turnover_threshold: 0.01  # Min change to trigger rebalance

  rebalance:
    frequency: "daily"
    transaction_cost: 0.0003  # 0.03% per trade

  data:
    interval: "daily"
    lookback_days: 3650  # ~10 years
    start_date: "2015-01-01"

  training:
    # Production uses 90/10 split (vs 70/15/15 research)
    train_split: 0.90
    val_split: 0.10
    test_split: 0.00  # Use all data for production

# Model Configuration (Phase 1 Extended)
model:
  algorithm: "SAC"
  observation_features: 173  # Phase 1 config (NOT Phase 4's 204)

  network:
    architecture: [256, 256]
    activation: "relu"

  hyperparameters:
    learning_rate: 1.0e-4
    gradient_steps: 1
    batch_size: 256
    buffer_size: 100000
    tau: 0.01
    gamma: 0.99
    ent_coef: "auto_0.1"

  training:
    total_timesteps: 1000000
    eval_freq: 10000
    n_eval_episodes: 10

  normalization:
    use_vecnormalize: true
    norm_obs: true
    norm_reward: true
    clip_obs: 10.0
    clip_reward: 10.0

# Environment Configuration
environment:
  lookback_window: 30  # Days of historical returns
  initial_capital: 100000

  observation_space:
    bounds: [-10.0, 10.0]  # Bounded observation space

  reward:
    scale_factor: 100  # Scale returns ×100
    clip_range: [-20, 20]
    sharpe_weight: 0.1
    turnover_penalty: 0.1
    turnover_threshold: 0.5

# Production Deployment Settings
deployment:
  status: "development"  # development | paper_trading | live

  capital:
    initial: 100000
    scale_after_paper_trading: 500000  # If successful

  execution:
    trade_time: "09:20"  # IST (after market opens)
    order_type: "limit"
    limit_offset: 0.005  # 0.5% from last close
    cancel_after_minutes: 30

  monitoring:
    log_level: "INFO"
    alert_email: null  # Configure for production
    alert_sms: null
